# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Creating cloudformation stack'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'awsconnection'
    regionName: 'ap-south-1'
    stackName: 'RDSEncrypt'
    templateSource: 'file'
    templateFile: 'RDS.yml'
    templateParametersFile: 'input.json'